name: dml-gat2
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
  - pyg
dependencies:
  - python=3.8
  - pytorch=1.10
  - torchvision
  - cudatoolkit=11.3
  - pyg
  - einops
  - numpy
  - matplotlib
  - nvidia-apex